// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9z6dTMP0k5hYrLa8Eap_BWbPd5NCbqI',
    appId: '1:897926330915:web:b4708f5017a62d240d0f96',
    messagingSenderId: '897926330915',
    projectId: 'khyaalapp',
    authDomain: 'khyaalapp.firebaseapp.com',
    storageBucket: 'khyaalapp.appspot.com',
    measurementId: 'G-HN3M45M13C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCxSDwZrjoH8VejaJBwqMCSb-jDALw6I',
    appId: '1:897926330915:android:47cdf39a16f056990d0f96',
    messagingSenderId: '897926330915',
    projectId: 'khyaalapp',
    storageBucket: 'khyaalapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7svLY0yaYiXyD3yZXuwqDZLnkLau4tuE',
    appId: '1:897926330915:ios:5297326b63af9fa00d0f96',
    messagingSenderId: '897926330915',
    projectId: 'khyaalapp',
    storageBucket: 'khyaalapp.appspot.com',
    iosBundleId: 'com.example.khyaalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7svLY0yaYiXyD3yZXuwqDZLnkLau4tuE',
    appId: '1:897926330915:ios:a9a781da7b654d180d0f96',
    messagingSenderId: '897926330915',
    projectId: 'khyaalapp',
    storageBucket: 'khyaalapp.appspot.com',
    iosBundleId: 'com.example.khyaalapp.RunnerTests',
  );
}
